/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { Empleado } from './models/empleado';
export { EstadosCivile } from './models/estados-civile';
export { TiposDocumento } from './models/tipos-documento';
