/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { EmpleadosService } from './services/empleados.service';
export { ListasService } from './services/listas.service';
