/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Empleado } from '../../models/empleado';

export interface EmpleadosCrearEmpleadoPost$Plain$Params {
      body?: Empleado
}

export function empleadosCrearEmpleadoPost$Plain(http: HttpClient, rootUrl: string, params?: EmpleadosCrearEmpleadoPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Empleado>> {
  const rb = new RequestBuilder(rootUrl, empleadosCrearEmpleadoPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Empleado>;
    })
  );
}

empleadosCrearEmpleadoPost$Plain.PATH = '/Empleados/CrearEmpleado';
