/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Empleado } from '../../models/empleado';

export interface EmpleadosActualizarEmpleadoPut$Json$Params {
      body?: Empleado
}

export function empleadosActualizarEmpleadoPut$Json(http: HttpClient, rootUrl: string, params?: EmpleadosActualizarEmpleadoPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Empleado>> {
  const rb = new RequestBuilder(rootUrl, empleadosActualizarEmpleadoPut$Json.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Empleado>;
    })
  );
}

empleadosActualizarEmpleadoPut$Json.PATH = '/Empleados/ActualizarEmpleado';
