/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadosCivile } from '../models/estados-civile';
import { TiposDocumento } from '../models/tipos-documento';
export interface Empleado {
  apellidos?: string | null;
  fechaNacimiento?: string | null;
  id?: number;
  idEstadoCivil?: number | null;
  idEstadoCivilNavigation?: EstadosCivile;
  idTipoDocumento?: number | null;
  idTipoDocumentoNavigation?: TiposDocumento;
  nombres?: string | null;
  numeroDocumento?: number | null;
  salario?: number | null;
}
