/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empleado } from '../models/empleado';
export interface EstadosCivile {
  empleados?: Array<Empleado> | null;
  id?: number;
  nombre?: string | null;
}
