/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { listasEstadosCivilesGet } from '../fn/listas/listas-estados-civiles-get';
import { ListasEstadosCivilesGet$Params } from '../fn/listas/listas-estados-civiles-get';
import { listasTiposDocumentoGet } from '../fn/listas/listas-tipos-documento-get';
import { ListasTiposDocumentoGet$Params } from '../fn/listas/listas-tipos-documento-get';

@Injectable({ providedIn: 'root' })
export class ListasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listasEstadosCivilesGet()` */
  static readonly ListasEstadosCivilesGetPath = '/Listas/EstadosCiviles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listasEstadosCivilesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  listasEstadosCivilesGet$Response(params?: ListasEstadosCivilesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return listasEstadosCivilesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listasEstadosCivilesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listasEstadosCivilesGet(params?: ListasEstadosCivilesGet$Params, context?: HttpContext): Observable<void> {
    return this.listasEstadosCivilesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listasTiposDocumentoGet()` */
  static readonly ListasTiposDocumentoGetPath = '/Listas/TiposDocumento';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listasTiposDocumentoGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  listasTiposDocumentoGet$Response(params?: ListasTiposDocumentoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return listasTiposDocumentoGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listasTiposDocumentoGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listasTiposDocumentoGet(params?: ListasTiposDocumentoGet$Params, context?: HttpContext): Observable<void> {
    return this.listasTiposDocumentoGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
